theme: jekyll-theme-minimal
title:  Yanzhao Xie
name: Biography
description: >
  <img src="me.png"  alt="photo" height="260" align="center"/>
  <center>Ph.D Candidate,</center>
  <center>Huazhong University of Science and Technology (HUST),</center>
  <center>Key Laboratory of Information Storage System, Ministry Of Education,</center>
  <center>Wuhan National Laboratory for Optoelectronics (WNLO),</center>
  <center>Intelligent Cloud Storage Joint Research Center of HUST and Tencent Inc.</center>
show_downloads: false
# logo: ./me.png
